name: upload Azure function zip to Azure storage account
on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  upload-azure-function-zip:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Copy 'src' directory and rename it 'logzio_function'
        run: |
          cp -R src logzio_function
      - name: Azure Login
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
      - uses: actions/setup-node@v2
        with:
          node-version: '16'
      - name: Create 'logzio_function' zip file that contains the function package
        run: |
          npm i -g azure-functions-core-tools@4 --unsafe-perm true
          cd logzio_function
          func pack --build-native-deps --python
          cp logzio_function.zip ../
      - name: Upload 'logzio_function' zip file to Azure storage
        uses: azure/CLI@v1
        with:
          inlineScript: |
            az storage blob upload --overwrite true --account-name logzioblobtrigger --account-key ${{ secrets.STORAGE_ACCOUNT_KEY }} -f logzio_function.zip -c logzio -n logzio_function.zip
