name: Automatic tests, code-coverage and auto-deployment files upload to S3
on:
  workflow_dispatch:
  push:
    branches:
      - master
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
      - uses: actions/setup-node@v2
        with:
          node-version: '14'
      - name: Zip
        run: |
          npm install azure-cli
          cd src
          func pack
          cp src.zip ../logzio_function.zip
      - name: Azure CLI script
        uses: azure/CLI@v1
        with:
          azcliversion: 2.0.72
          inlineScript: |
            az storage blob upload --account-name shiranstorage --account-key RRcBXAslm7HcP0iyq9MBfVJ/9KceF8U/ZOV/S0np+YaZi7ysa9w+1FgMTMs3u+18xfUY3YcFwFf/bID6xacT7Q== -f logzio_function.zip -c logzio -n logzio_function.zip