name: Automatic tests, code-coverage and Azure function zip upload to Azure storage
on:
  workflow_dispatch:
  push:
    branches:
      - main
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: '3.x'
      - name: Copy 'src' directory and rename it 'logzio_function'
        run: |
          cp -R src logzio_function
      - name: Add Logz.io url and token to tests config file
        run: |
          sed -i 's#LOGZIO_URL\b#${{ secrets.LOGZIO_URL }}#1' tests/config.yaml
          sed -i 's/LOGZIO_TOKEN\b/${{ secrets.LOGZIO_TOKEN }}/1' tests/config.yaml
      - name: Run unit tests
        run: |
          pip install pytest
          pip install httpretty
          pip install requests
          pip install azure-functions
          pip install pyyaml
          pip install pytest-cov
          pytest --cov-report xml:code_coverage.xml --cov=src tests/azure_function_tests.py
      - name: Code-coverage
        run: |
          # Get line-rate
          line_rate=$(head -2 code_coverage.xml | tail -1 | egrep -o "line-rate=\"[0-1]\.?[0-9]*\"" | egrep -o "[0-1]\.?[0-9]*")

          # Print line-rate
          echo | awk -v num=$line_rate '{ printf "line-rate: %d%\n", (num * 100) }'

          # Check code-coverage conditions
          echo | awk -v num=$line_rate '{ if (num < 0.8) { printf "line-rate is less than 80%"; exit 1 } else { exit 0 }}'
          exit_code=$?
          if [ $exit_code -eq 1 ]; then
            exit 1
          fi
      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
      - uses: actions/setup-node@v2
        with:
          node-version: '14'
      - name: Create 'logzio_function' zip file that contains the function package
        run: |
          npm i -g azure-functions-core-tools@3 --unsafe-perm true
          cd logzio_function
          func pack --build-native-deps --python
          cp logzio_function.zip ../
      - name: Upload 'logzio_function' zip file to Azure storage
        uses: azure/CLI@v1
        with:
          azcliversion: 2.0.72
          inlineScript: |
            az storage blob upload --account-name logzioazureblobtrigger --account-key ${{ secrets.STORAGE_ACCOUNT_KEY }} -f logzio_function.zip -c logzio -n logzio_function.zip