name: Automatic tests, code-coverage and logzio function zip upload to azure storage
on:
  workflow_dispatch:
  push:
    branches:
      - master
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: '3.x'
      - name: Add Logz.io url and token to tests config file
        run: |
          sed -i 's#LOGZIO_URL\b#${{ secrets.LOGZIO_URL }}#1' tests/config.yaml
          sed -i 's/LOGZIO_TOKEN\b/${{ secrets.LOGZIO_TOKEN }}/1' tests/config.yaml
      - name: Run unit tests
        run: |
          pip install pytest
          pip install httpretty
          pip install requests
          pip install pyyaml
          pip install pytest-cov
          pytest --cov=src tests/azure_function_tests.py | tee code_coverage.txt
      - name: Code-coverage
        run: |
          # Get code-coverage
          code_coverage=$(tail -4 code_coverage.txt | head -1 | egrep -o "[0-9]+" | tail -1)
          # Print code-coverage
          echo code-coverage: $code_coverage%
          # Check code-coverage condition
          echo | awk -v num=$code_coverage '{ if (num < 80) { printf "code_coverage is less than 80%"; exit 1 } else { exit 0 }}'
          exit_code=$?
          if [ $exit_code -eq 1 ]; then
            exit 1
          fi
      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
      - uses: actions/setup-node@v2
        with:
          node-version: '14'
      - name: Create logzio_function zip file that contains the function package
        run: |
          npm i -g azure-functions-core-tools@3 --unsafe-perm true
          cd src
          func pack
          cp src.zip ../logzio_function.zip
      - name: Upload logzio_function zip file to azure storage
        uses: azure/CLI@v1
        with:
          azcliversion: 2.0.72
          inlineScript: |
            az storage blob upload --account-name shiranstorage --account-key ${{ secrets.STORAGE_ACCOUNT_KEY }} -f logzio_function.zip -c logzio -n logzio_function.zip